/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { AiPhoneAgentService } from "../aiPhoneAgent.service";
import { AiPhoneAgentCreateInput } from "./AiPhoneAgentCreateInput";
import { AiPhoneAgent } from "./AiPhoneAgent";
import { AiPhoneAgentFindManyArgs } from "./AiPhoneAgentFindManyArgs";
import { AiPhoneAgentWhereUniqueInput } from "./AiPhoneAgentWhereUniqueInput";
import { AiPhoneAgentUpdateInput } from "./AiPhoneAgentUpdateInput";
import { ConversationFindManyArgs } from "../../conversation/base/ConversationFindManyArgs";
import { Conversation } from "../../conversation/base/Conversation";
import { ConversationWhereUniqueInput } from "../../conversation/base/ConversationWhereUniqueInput";

export class AiPhoneAgentControllerBase {
  constructor(protected readonly service: AiPhoneAgentService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: AiPhoneAgent })
  async createAiPhoneAgent(
    @common.Body() data: AiPhoneAgentCreateInput
  ): Promise<AiPhoneAgent> {
    return await this.service.createAiPhoneAgent({
      data: data,
      select: {
        active: true,
        conversationHistory: true,
        createdAt: true,
        id: true,
        language: true,
        name: true,
        responseScript: true,
        speechSettings: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [AiPhoneAgent] })
  @ApiNestedQuery(AiPhoneAgentFindManyArgs)
  async aiPhoneAgents(@common.Req() request: Request): Promise<AiPhoneAgent[]> {
    const args = plainToClass(AiPhoneAgentFindManyArgs, request.query);
    return this.service.aiPhoneAgents({
      ...args,
      select: {
        active: true,
        conversationHistory: true,
        createdAt: true,
        id: true,
        language: true,
        name: true,
        responseScript: true,
        speechSettings: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: AiPhoneAgent })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async aiPhoneAgent(
    @common.Param() params: AiPhoneAgentWhereUniqueInput
  ): Promise<AiPhoneAgent | null> {
    const result = await this.service.aiPhoneAgent({
      where: params,
      select: {
        active: true,
        conversationHistory: true,
        createdAt: true,
        id: true,
        language: true,
        name: true,
        responseScript: true,
        speechSettings: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: AiPhoneAgent })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateAiPhoneAgent(
    @common.Param() params: AiPhoneAgentWhereUniqueInput,
    @common.Body() data: AiPhoneAgentUpdateInput
  ): Promise<AiPhoneAgent | null> {
    try {
      return await this.service.updateAiPhoneAgent({
        where: params,
        data: data,
        select: {
          active: true,
          conversationHistory: true,
          createdAt: true,
          id: true,
          language: true,
          name: true,
          responseScript: true,
          speechSettings: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: AiPhoneAgent })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteAiPhoneAgent(
    @common.Param() params: AiPhoneAgentWhereUniqueInput
  ): Promise<AiPhoneAgent | null> {
    try {
      return await this.service.deleteAiPhoneAgent({
        where: params,
        select: {
          active: true,
          conversationHistory: true,
          createdAt: true,
          id: true,
          language: true,
          name: true,
          responseScript: true,
          speechSettings: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/conversations")
  @ApiNestedQuery(ConversationFindManyArgs)
  async findConversations(
    @common.Req() request: Request,
    @common.Param() params: AiPhoneAgentWhereUniqueInput
  ): Promise<Conversation[]> {
    const query = plainToClass(ConversationFindManyArgs, request.query);
    const results = await this.service.findConversations(params.id, {
      ...query,
      select: {
        aiPhoneAgent: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        endTime: true,
        id: true,
        startTime: true,
        transcript: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/conversations")
  async connectConversations(
    @common.Param() params: AiPhoneAgentWhereUniqueInput,
    @common.Body() body: ConversationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      conversations: {
        connect: body,
      },
    };
    await this.service.updateAiPhoneAgent({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/conversations")
  async updateConversations(
    @common.Param() params: AiPhoneAgentWhereUniqueInput,
    @common.Body() body: ConversationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      conversations: {
        set: body,
      },
    };
    await this.service.updateAiPhoneAgent({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/conversations")
  async disconnectConversations(
    @common.Param() params: AiPhoneAgentWhereUniqueInput,
    @common.Body() body: ConversationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      conversations: {
        disconnect: body,
      },
    };
    await this.service.updateAiPhoneAgent({
      where: params,
      data,
      select: { id: true },
    });
  }
}
